package de.hscoburg.evelin.secat.model.xml;

/**
 * Klasse dient zum beschreiben des grundaufbaues eines Fragebogens innerhalb des open QUestionarie Formats
 * 
 * @author zuch1000
 * 
 */
public class FragebogenXML extends BaseXML {

	private String fragebogenName;

	private static final String START_XML = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
			+ "<!DOCTYPE QUESTIONNAIRE [\n"
			+ "  <!ELEMENT QUESTIONNAIRE (META*,QUESTIONBLOCK,INDICATOR*,PERMUTATION*)>\n"
			+ "  <!ATTLIST QUESTIONNAIRE NAME CDATA #REQUIRED>\n"
			+ "  <!ATTLIST QUESTIONNAIRE DESCRIPTION CDATA #IMPLIED>\n"
			+ "  <!ATTLIST QUESTIONNAIRE ABOUT CDATA #IMPLIED>\n"
			+ "  <!ATTLIST QUESTIONNAIRE VERSION CDATA \"13\">\n"
			+ "      <!ELEMENT META EMPTY>\n"
			+ "      <!ATTLIST META KEY CDATA #REQUIRED>\n"
			+ "      <!ATTLIST META VALUE CDATA #REQUIRED>\n"
			+ "      <!ELEMENT INDICATOR (META)*>\n"
			+ "      <!ATTLIST INDICATOR NAME CDATA #REQUIRED>\n"
			+ "      <!ATTLIST INDICATOR USERID CDATA #IMPLIED>\n"
			+ "      <!ATTLIST INDICATOR QUESTIONINDICES CDATA #REQUIRED>\n"
			+ "      <!ATTLIST INDICATOR IMPORTANCE CDATA #REQUIRED>\n"
			+ "      <!ATTLIST INDICATOR PLACE CDATA #REQUIRED>\n"
			+ "      <!ATTLIST INDICATOR TYPE CDATA #REQUIRED>\n"
			+ "      <!ELEMENT PAGEBREAK (META)*>\n"
			+ "      <!ELEMENT QUESTIONBLOCK ((META)*,(FILTERQUESTION)*,(MCQUESTION|SCALEDQUESTION|NUMBERQUESTION|FREEQUESTION|HEADING|EXPLANATION|QUESTIONBLOCK|PAGEBREAK|IMAGE)*)>\n"
			+ "      <!ATTLIST QUESTIONBLOCK NAME CDATA #REQUIRED>\n" + "      <!ATTLIST QUESTIONBLOCK RANDOMIZED CDATA #REQUIRED>\n"
			+ "      <!ATTLIST QUESTIONBLOCK PLACE CDATA #REQUIRED>\n" + "      <!ATTLIST QUESTIONBLOCK TARGETLAYER CDATA #REQUIRED>\n"
			+ "      <!ELEMENT FILTERQUESTION (FILTERANSWER)*>\n" + "      <!ATTLIST FILTERQUESTION PLACE CDATA #REQUIRED>\n"
			+ "      <!ATTLIST FILTERQUESTION QUESTION CDATA #REQUIRED>\n" + "      <!ATTLIST FILTERQUESTION FILTERTYPE CDATA #REQUIRED>\n"
			+ "      <!ATTLIST FILTERQUESTION RELATION2NEXT CDATA #REQUIRED>\n" + "      <!ELEMENT FILTERANSWER (META)*>\n"
			+ "        <!ATTLIST FILTERANSWER TEXT CDATA #REQUIRED>\n" + "      <!ELEMENT EXPLANATION (META)*>\n"
			+ "      <!ATTLIST EXPLANATION NAME CDATA #REQUIRED>\n" + "      <!ATTLIST EXPLANATION PLACE CDATA #REQUIRED>\n"
			+ "      <!ATTLIST EXPLANATION TUTOR CDATA #REQUIRED>\n" + "      <!ELEMENT HEADING (META)*>\n" + "      <!ATTLIST HEADING NAME CDATA #REQUIRED>\n"
			+ "      <!ATTLIST HEADING PLACE CDATA #REQUIRED>\n" + "      <!ATTLIST HEADING TUTOR CDATA #REQUIRED>\n"
			+ "      <!ELEMENT MCQUESTION ((META)*,(ANSWER)*)>\n" + "      <!ATTLIST MCQUESTION TEXT CDATA #REQUIRED>\n"
			+ "      <!ATTLIST MCQUESTION ZWANG CDATA #REQUIRED>\n" + "      <!ATTLIST MCQUESTION TUTOR CDATA #REQUIRED>\n"
			+ "      <!ATTLIST MCQUESTION PLACE CDATA #REQUIRED>\n" + "      <!ATTLIST MCQUESTION WEIGHT CDATA #IMPLIED>\n"
			+ "      <!ATTLIST MCQUESTION REFUSEANSWER CDATA #IMPLIED>\n" + "      <!ATTLIST MCQUESTION OTHERANSWER CDATA #IMPLIED>\n"
			+ "      <!ATTLIST MCQUESTION NOTELABEL CDATA #IMPLIED>\n" + "      <!ATTLIST MCQUESTION NOTE CDATA #IMPLIED>\n"
			+ "      <!ELEMENT ANSWER (META)*>\n" + "        <!ATTLIST ANSWER TEXT CDATA #REQUIRED>\n" + "        <!ATTLIST ANSWER PLACE CDATA #REQUIRED>\n"
			+ "        <!ATTLIST ANSWER WEIGHT CDATA #IMPLIED>\n" + "      <!ELEMENT FREEQUESTION ((META)*, IMAGEDATA*)>\n"
			+ "      <!ATTLIST FREEQUESTION TEXT CDATA #REQUIRED>\n" + "      <!ATTLIST FREEQUESTION PUBLIC CDATA #REQUIRED>\n"
			+ "      <!ATTLIST FREEQUESTION ZWANG CDATA #REQUIRED>\n" + "      <!ATTLIST FREEQUESTION TUTOR CDATA #REQUIRED>\n"
			+ "      <!ATTLIST FREEQUESTION PLACE CDATA #REQUIRED>\n" + "      <!ATTLIST FREEQUESTION ROWS CDATA #IMPLIED>\n"
			+ "      <!ATTLIST FREEQUESTION NOTELABEL CDATA #IMPLIED>\n" + "      <!ATTLIST FREEQUESTION NOTE CDATA #IMPLIED>\n"
			+ "      <!ATTLIST FREEQUESTION FIELD_IMAGE_WIDTH CDATA #IMPLIED>\n" + "      <!ATTLIST FREEQUESTION FIELD_IMAGE_HEIGHT CDATA #IMPLIED>\n"
			+ "      <!ELEMENT NUMBERQUESTION (META)*>\n" + "      <!ATTLIST NUMBERQUESTION TEXT CDATA #REQUIRED>\n"
			+ "      <!ATTLIST NUMBERQUESTION ZWANG CDATA #REQUIRED>\n" + "      <!ATTLIST NUMBERQUESTION TUTOR CDATA #REQUIRED>\n"
			+ "      <!ATTLIST NUMBERQUESTION MIN CDATA #REQUIRED>\n" + "      <!ATTLIST NUMBERQUESTION MAX CDATA #REQUIRED>\n"
			+ "      <!ATTLIST NUMBERQUESTION PLACE CDATA #REQUIRED>\n" + "      <!ATTLIST NUMBERQUESTION NOTELABEL CDATA #IMPLIED>\n"
			+ "      <!ATTLIST NUMBERQUESTION NOTE CDATA #IMPLIED>\n" + "      <!ELEMENT SCALEDQUESTION ((META)*,(ANSWER)*)>\n"
			+ "      <!ATTLIST SCALEDQUESTION TEXT CDATA #REQUIRED>\n" + "      <!ATTLIST SCALEDQUESTION ZWANG CDATA #REQUIRED>\n"
			+ "      <!ATTLIST SCALEDQUESTION TUTOR CDATA #REQUIRED>\n" + "      <!ATTLIST SCALEDQUESTION MINTEXT CDATA #REQUIRED>\n"
			+ "      <!ATTLIST SCALEDQUESTION MAXTEXT CDATA #REQUIRED>\n" + "      <!ATTLIST SCALEDQUESTION OPTIMUM CDATA #REQUIRED>\n"
			+ "      <!ATTLIST SCALEDQUESTION STEPS CDATA #REQUIRED>\n" + "      <!ATTLIST SCALEDQUESTION PLACE CDATA #REQUIRED>\n"
			+ "      <!ATTLIST SCALEDQUESTION WEIGHT CDATA #IMPLIED>\n" + "      <!ATTLIST SCALEDQUESTION REFUSEANSWER CDATA #IMPLIED>\n"
			+ "      <!ATTLIST SCALEDQUESTION NOTELABEL CDATA #IMPLIED>\n" + "      <!ATTLIST SCALEDQUESTION NOTE CDATA #IMPLIED>\n"
			+ "      <!ELEMENT IMAGE ((META)*,(IMAGEDATA))>\n" + "      <!ATTLIST IMAGE NAME CDATA #REQUIRED>\n"
			+ "      <!ATTLIST IMAGE PLACE CDATA #REQUIRED>\n" + "      <!ATTLIST IMAGE WIDTH CDATA #REQUIRED>\n"
			+ "      <!ATTLIST IMAGE HEIGHT CDATA #REQUIRED>\n" + "      <!ELEMENT IMAGEDATA (#PCDATA)>\n"
			+ "      <!ATTLIST IMAGEDATA MIMETYPE CDATA #REQUIRED>\n" + "      <!ELEMENT PERMUTATION ((META)*,(EXTERNALIDREF)*)>\n"
			+ "      <!ATTLIST PERMUTATION NAME CDATA #REQUIRED>\n" + "      <!ELEMENT EXTERNALIDREF EMPTY>\n"
			+ "      <!ATTLIST EXTERNALIDREF ID CDATA #REQUIRED>\n" + "      <!ATTLIST EXTERNALIDREF NO CDATA #REQUIRED>\n"
			+ "      <!ATTLIST EXTERNALIDREF ANSWERS CDATA #REQUIRED>\n" + "]>\n";

	public FragebogenXML(String name) {
		fragebogenName = name;
	}

	/**
	 * Gibt den Starttag zurueck.
	 * 
	 * @param builder
	 *            - {@link StringBuilder} zum speichern des Tags.
	 */
	@Override
	public void getStartXML(StringBuilder builder) {

		builder.append(START_XML);

		builder.append("<QUESTIONNAIRE DESCRIPTION=\"\" ABOUT=\"\" VERSION=\"13\" NAME=\"" + XML_ESCAPER.translate(fragebogenName) + "\">\n");

	}

	/**
	 * Gibt den Endtag zurueck.
	 * 
	 * @param builder
	 *            - {@link StringBuilder} zum speichern des Tags.
	 */
	@Override
	public void getEndXML(StringBuilder builder) {
		builder.append("</QUESTIONNAIRE>\n\n");
	}

}
